### ISSUE TITLE
security email from facebook

### ISSUE THREAD

**Issue by joske** [jgeboski/purple-facebook#100]
Hi,

I'm using this, but I get a security mail from facebook saying I logged in from Facebook for android near Israel, but I live in Belgium. In the details, I can see the IP address matches mine. Is this an artefact from facebook's IP-to-location matching?

This is a bit scary, maybe you can document this?

**Comment by dequis** [comment]
>In the details, I can see the IP address matches mine. Is this an artefact from facebook's IP-to-location matching?

Well, if it matches yours, then it's definitely a problem with their ip-to-location matching. That whole procedure is a matter of guessing, after all.

I think adding a few mentions of the stuff in the [security](https://www.facebook.com/settings?tab=security) page of the facebook settings might help. "App passwords" and "where you're logged in", mainly

**Comment by joske** [comment]
Also, it is seen as "Facebook for Android". Is that what you expect?

**Comment by dequis** [comment]
Yeah, also worth mentioning. This plugin tries to behave just like the facebook messenger app for android.

**Comment by dequis** [comment]
Added [faq entry](https://github.com/jgeboski/purple-facebook/wiki#i-received-an-emailsms-saying-i-logged-in-from-a-new-location) to the wiki. I think it should be clear enough but poke me if you'd like to reword anything (we locked the wiki to collaborators since some changes weren't exactly... helpful)
