### ISSUE TITLE
How can I use purple-facebook as facebook API in my application?

### ISSUE THREAD

**Issue by y3g0r** [jgeboski/purple-facebook#126]
@jgeboski, Thanks a lot for such a great work. I was able to run it on my linux host under pidgin and it works great! 

But my main purpose is more to use this library in my own application than to use it as the messenger alternative.

I have Contact centre application with RESTfull API.
I'd like to write facebook connector for my application to allow exchange customer's requests from facebook to Contact centre and client's answers from application back to client in facebook.
Can you give any suggestions how can I implement this. Also I'm not pretty familiar with C (bigger experience in OOP languages). How can I bind this C library with languages like C++/Java/Python etc.
I downloaded source code but didn't find there familiar starting point, only some macro definitions. As I understand it should be used in bind with libpurple. Should I use pidgin API? 
Maybe you can point some useful book or article. 
Thanks a lot for your advices. 
Sorry for my English. 
Yegor

**Comment by dequis** [comment]
You could write libpurple client. You need to know C to do this. See the [example null client][1] included with pidgin. C++ isn't recommended due to ABI differences, things will break in subtle ways. Using java or python isn't really possible, last time i checked the python bindings didn't work at all.

You could also control a pidgin client through [DBUS][2], or you could connect to a third party client such as spectrum (XMPP) or bitlbee (IRC), having configured them properly first.

[1]: https://hg.pidgin.im/pidgin/main/raw-file/79fe6b95f105/libpurple/example/nullclient.c
[2]: https://developer.pidgin.im/wiki/DbusHowto

**Comment by y3g0r** [comment]
@dequis, Thanks a lot for your advices. I'll try to get use to DBUS. If I'll be able to exchange messages through pidgin using DBUS from my client on python it seems to be pretty simple way to achieve my goal.
Again, thanks for advices!!
Cheers!
