### ISSUE TITLE
Quote character showing up on Facebook as &quot;

### ISSUE THREAD

**Issue by mike552s** [jgeboski/purple-facebook#139]
When sending messages from the latest version of the facebook plugin, a quote character (") shows up in Facebook's web chat and Android Messenger app chat as \&quot;  When reversed, sending from real facebook to pidgin works as expected where a quote (") shows up as a quote character (").

For example, sending "Test" shows up in Facebook as \&quot;Test\&quot;

Facebook
	Author: (null)
	Version: a34b993324e4
	Website: https://github.com/jgeboski/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

**Comment by dequis** [comment]
That's not the latest, that was released two months ago. You're 13 releases behind.

After upgrading you should remove then readd the pidgin account to ensure the connection is configured correctly.

**Comment by mike552s** [comment]
Thanks for the info.  Unfortunately not everyone can build their own copy of software so I download the pre-built version. The last pre-build version available is dated July 18 so I guess I will try that version which is 12 days newer than the version I had.

**Comment by dequis** [comment]
I don't know what platform you're using or where you're getting those pre-built packages from, but you might want to re-read the installation instructions since you're definitely getting it from the wrong place.

* https://github.com/jgeboski/purple-facebook/wiki/Installing-on-Windows
* https://github.com/jgeboski/purple-facebook/wiki/Installing-on-*NIX
