### ISSUE TITLE
Profile link received twice

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#142]
If someone sends a profile link in a chat, the link is received twice:
https://www.facebook.com/profilename?fref=ts
https://www.facebook.com/profilename

Please fix as in #109 (#109 needs additional fixing, see here: https://github.com/jgeboski/purple-facebook/issues/109#issuecomment-141691327)

**Comment by Smile4ever** [comment]
This is the case too with normal URLs where an thumbnail is generated (two times the same URL):
http://google.com
http://google.com

**Comment by jgeboski** [comment]
I am *only* able to recreate this issue with a profile URL with `?fref=ts` appended to the end.  This is likely due to the "special handling of profile links within the chat.  Any other URL seems to work fine, including `google.com`.  There are some small quarks, for example, Facebook will turn `?foo=` into `?foo`.

The plugin needs match URL parameters directly, rather than as a string.  It also needs to search the message text for the URL as well, instead of assuming the message is the URL.

**Comment by jgeboski** [comment]
After poking around at a fix for this, I realized that any profile link with parameters will cause this to happen. Moreover, I am fairly certain this is not the only kind of Facebook link this issue will happen with. Unfortunately, we cannot just strip the parameters off of any Facebook link, as many of the Facebook links require them. I also have no interest in having a never ending set of static conditions, which a link must go through before it is displayed. This is a *trivial* and *uncommon* issue, which does not warrant the time or effort involved.
