### ISSUE TITLE
Group chats not sorted

### ISSUE THREAD

**Issue by lmfardin** [jgeboski/purple-facebook#162]
I use a plugin called Extended B-List Sort in order to have more criteria to sort my friends list. However, these criteria don't seem to work for Facebook group chats.

**Comment by dequis** [comment]
Can you provide some examples?

What criteria did you use, what did you expect, and what did you get instead?

**Comment by lmfardin** [comment]
My criteria was log size. When I sent and received some messages, I was expecting that group to move through my friends list, but it got stuck at the top. 


     Em Domingo, 1 de Novembro de 2015 19:25, dx <notifications@github.com> escreveu:
   

 Can you provide some examples?What criteria did you use, what did you expect, and what did you get instead?—

**Comment by jgeboski** [comment]
Are the logs being updated, or are they disabled/empty?

**Comment by jgeboski** [comment]
Is this issue only present with the log size ordering? Do these group chats have a large number of users in them?

It is worth nothing that with group chats, if there are a lot of people, the joining/parting messages are logged when entering the group chat. This has been fixed in a recent patch, [2a83ef0](https://bitbucket.org/pidgin/main/commits/2a83ef0aed865b68e4412bfd7ec27854bea694bd), and will appear in the next release. This could be causing the log size of these group chats to be rather large if there are a lot of users.

**Comment by jgeboski** [comment]
Any update on this issue?

**Comment by dequis** [comment]
ping

**Comment by lmfardin** [comment]
Sorry for taking so long to respond.I haven't been into group chats nowadays, but I'll let you know if issue happens again. 

    Em Sábado, 30 de Janeiro de 2016 16:08, dx <notifications@github.com> escreveu:
 

 ping—

**Comment by jgeboski** [comment]
Closing this for now. Reopen if the issue is still persistent.
