### ISSUE TITLE
debianize package

### ISSUE THREAD

**Issue by blue119** [jgeboski/purple-facebook#166]
I am a debian user and sometimes I have to talk with my friend with facebook IM, but I don't like to browse facebook.com.

Unfortunately, I cann't find the plugin in any debian package pool, but I saw there is a debianize folder in. and I just saw one guy  Francesco who filed a [WNPP wishlist](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803473) to Debain BTS. So I thought it is a good time to promote this plugin to Debian next release pool.

If no one has time to do this, I am willing to be the debianize maintainer of purple-facebook.

**Comment by pochy-ja** [comment]
See here[1] a packages for Debian 7 and 8.

[1] https://jgeboski.github.io/#package-repositories

**Comment by blue119** [comment]
Hi pocy-js,

Sounds good. Seems the debianize is ready. We are only lack of the paperwork of Debian RFS.

How about let us push the package to official repository and closed the Debian BTS for purple-faceboot?

It will be better, if user can find the package from official repository. :)

Thanks,

**Comment by pochy-ja** [comment]
That is sound good for me, but maybe @jgeboski, who is the responsible of the project, could answer this question.

**Comment by jgeboski** [comment]
If adding the project to Debian was not such a process, I would say go for it. However, the effort required is not worth it, as this project is only "temporary." Upon the next major Pidgin release, this project will become irrelevant since all of the Facebook stuff was merged into [mainline][l1] Pidgin. And as a result, I will no longer maintain this project, in order to focus all of my efforts on upstream code. It will likely be a little while until the next major Pidgin release, but in the meantime, my third party Debian repository should suffice.

[l1]: https://bitbucket.org/pidgin/main/commits/8059ab4da709d116ee4d96d91441b383729e69d0

**Comment by dequis** [comment]
The purple3 release might take a few months, or a few years. Even after it's released it might take a while before purple2 is completely discontinued (all plugins ported, etc)

I'd say that if someone from debian is willing to take care of the debian paperwork, there's no reason for us to stop them.

**Comment by jgeboski** [comment]
Fair enough, @dequis. If you are really interested in handling everything, @blue119, go ahead.

**Comment by blue119** [comment]
thanks for you support. I can deal with Debian new package process and any progress I will update here.

**Comment by jgeboski** [comment]
Given this is outside the development scope of this plugin, I am going to close this issue. Feel free to reply to the ticket with updates on the matter.
