### ISSUE TITLE
Logging out on Facebook.com causes purple-facebook to disconnect as well

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#171]
Logging out on Facebook.com causes purple-facebook to disconnect as well with the error message "failed to write data".

**Comment by dequis** [comment]
Uhh... okay? Log back in?

**Comment by Smile4ever** [comment]
Logging out on the Facebook website should not disconnect purple-facebook.

**Comment by KubaHudzik** [comment]
> Uhh... okay? Log back in?
> dequis 

Seriously? That's your answer? I hope that you're not working as a developer because such approach is really bad. Software should work correctly and telling somebody to "log back in" (which is obvious) is the stupidest answer ever. And yes, I know that this is open source project but if you want to make such comments you'd better shut up.

**Comment by dequis** [comment]
If the server decides to disconnect us because the user logged out from the website, there's nothing we can do about it. This isn't a problem about this software not working correctly.

Also, please chill out.

**Comment by Smile4ever** [comment]
Is this somehow related tot the architecture of purple-facebook which presents itself as a Facebook.com client?

**Comment by KubaHudzik** [comment]
But it is **a problem**. And it's quite odd, since you can have two or more logging session from one device

**Comment by jgeboski** [comment]
There is nothing we can do to prevent the MQTT stream from dying when logging out. I am sure you have also noticed the connection will die every 24-48 hours. Again, we cannot prevent this from happening. The only thing we can do, which will happen in due time, is silently reconnect the MQTT stream in the background.

It is worth noting, this is a protocol designed for mobile devices, which reconnect all the time.

**Comment by dequis** [comment]
Also, the same thing happens with the XMPP gateway (which still works in non-libpurple clients). It's just facebook logging out everywhere.

Give it a few seconds and it will reconnect automatically.

**Comment by RushJet1** [comment]
Whenever this happens to me, clicking "reconnect" doesn't work - I have to disable the Facebook account and then re-enable it.  It's not a huge deal and only happens once every 1-2 days, like @jgeboski said.

**Comment by dequis** [comment]
>clicking "reconnect" doesn't work

What do you mean by "doesn't work"? What happens when you do that? Does it get stuck? Does it throw an error immediately?

>and only happens once every 1-2 days

Are you sure you're talking about the same issue of this ticket? What jgeboski mentioned about "every 1-2 days" is just the server disconnecting us for reasons other than clicking logging out in the website. There are other issues covering reconnection problems, such as #143, if that's the case. But as far as I know reconnecting just works with this particular issue.

**Comment by jgeboski** [comment]
Closing this in favor of #186.
