### ISSUE TITLE
Duplicate messages using latest purple-facebook

### ISSUE THREAD

**Issue by Smile4ever** [jgeboski/purple-facebook#199]
If you would check the last ~10 messages instead of only the last message to deduplicate, this would be solved too:
![bug-purple-facebook-priv](https://cloud.githubusercontent.com/assets/544411/12371916/a49ab960-bc44-11e5-8369-e356d1360498.png)

**Comment by jgeboski** [comment]
This still would not provide a bullet proof solution. Messages can be duplicated after differing periods of time as well, rather than just sequentially. So, rather than checking the last *n* messages, it really needs to check the messages over a time span. Even still, it would be hard to get this timing right as well.

The proper solution, as noted in [ad2ee74][r1], is to use the latest revision of the Facebook Messenger Protocol. The only reason [ad2ee74][r1] exists is because it is *very* simple, and it addresses the most common duplication case. I really have no interest in making things overly complex, especially when it will never provide a bullet proof solution. Moreover, it is not even a proper solution to the issue at hand.

[r1]: https://bitbucket.org/pidgin/main/commits/ad2ee74b913ae50e170b1d06413fa2a494a9ee76
