### ISSUE TITLE
Add facebook contacts to a new group by default

### ISSUE THREAD

**Issue by BoBeR182** [jgeboski/purple-facebook#37]
When you add the new facebook account to pidgin it automatically added all my facebook friends to a group called "buddies", instead of its own group called "facebook friends". Please change the default behaviour.

**Comment by jgeboski** [comment]
I talked to some of the other more seasoned pidgin developers about this.  Apparently, there is a sort of great debate as to handling grouping in this manner.  Since I plan to have bidirectional Facebook group support at some point, I am just going to leave this as is for now.  In the meantime, you will have to locally organize buddies.
