### ISSUE TITLE
Infinite scrollback of server-side logs

### ISSUE THREAD

**Issue by adnieman** [jgeboski/purple-facebook#51]
I know the API supports it, but would it be feasable to implement a messenger history that could be loaded through the API interface? It would be nice if we could have some backscroll that might have occurred while using our android messenger apps, or the web messaging interface.

**Comment by dequis** [comment]
I don't think this can happen in pidgin2 since purple2 doesn't provide a way for protocol plugins to do such thing, but it *could* be added to purple3 still, at least in theory, since its api is not stable yet.

I don't know what @jgeboski thinks about this feature (he might just close this to not have a ticket for something that can't be done), but i'm going to go ahead and change the ticket title to something more relevant, since by the title it sounds like you're requesting something that is in #9 already

**Comment by EionRobb** [comment]
@dequis isn't he just asking for offline message history, which is already in #9 ?

**Comment by adnieman** [comment]
No, I would much rather have the ability to have the last 10, 20, 30,
etc, messages load from the server, than to have a full local only
history. If I message from the android app, there is no message sync of
any kind. If I start conversation in one place, then boot my PC, I have
no history of the conversations. It would be nice to have that load
dynamically.

**Comment by EionRobb** [comment]
So a combination of offline history and self-sent messages?

**Comment by adnieman** [comment]
You know when you load up the Facebook Messenger app on Android for the
first time? It retrieves a certain number of messages to or from you and
the people you message with. This is the kind of thing that should
happen in most messenger applications, and it is lacking in most Pidgin
protocol plugins. The most recent messages to or from is pretty
standard. If the plugin needs more history, it grabs it and caches it
locally, like the Facebook Messenger Android app. I can message on the
web site, and my previous messages to or from me are available to in the
Android app. Same protocol. On protocol plugin init and login is when
this information can be grabbed. I know it adds considerable complexity,
but in the end, are we trying to meet minimums, or are we trying to
match or exceed quality?

**Comment by jgeboski** [comment]
This seems way outside the scope of this plugin.  This is more of a feature request that should be brought up with the Pidgin project directly.

**Comment by adnieman** [comment]
Really? Seems within the scope of the protocol plugin, as its
implemented in protocol. Is it because pidgin logs using html? Is it
because it would be too difficult to provide some local caching
backscroll to the plugin directly? Messages are ID'd, meaning each one
has a message identifier. It would not be out of scope for the plugin to
handle that directly, as each protocol should handle that directly.

**Comment by EionRobb** [comment]
This is what the conversation history plugin does; it displays previous
history in the conversation window

**Comment by jgeboski** [comment]
@adnieman I think what you mean is that you want to be able to is scroll up, and fetch a chunk of the messages history.  And repeat this process until there is no more history.  This functionality does not exist within libpurple.

Even if the plugin was to cache all the history, there would likely be enormous amount of history stored locally, especially with people with friends in the thousands.  Moreover, there are no such identifiers stuck to messages in libpurple, at least as far as I am aware.  There are however timestamps, but I do not even know if that can be easily retrieved from logs.  And the problem with timestamps is they can be inconsistent with RTCs which are not set correctly.  So, then the plugin has to do a bunch of nonstandard stuff (and likely a bunch of hackery) in order to make this happen.

If there was some sort of API within libpurple for this, I would gladly support it.  However, to my knowledge there is not (@EionRobb would likely know more on this).  You have to remember, this is a purple3 plugin, and I am attempting to get it mainlined at the end of the summer.  If there is a bunch of nonstandard (and likely inconsistent) features, the likelihood of the plugin getting merged drops.

**Comment by dequis** [comment]
Soooo... as i said originally...

>he might just close this to not have a ticket for something that can't be done

And it clearly can't be done. Nuke this?

**Comment by fangfufu** [comment]
I think this *might* be a bit off-topic. If you can fix "self-message" in the enhancement list, if one of the computer is on, everything that happened on Android client or the web interface will appear in that Pidgin instance. I don't know if this partly addresses @adnieman's request.

**Comment by jgeboski** [comment]
This is a good idea, there is just no sane way of implementing it.  For now I am closing this issue.
