### ISSUE TITLE
Semantiv versioning 

### ISSUE THREAD

**Issue by ad-m** [jgeboski/purple-facebook#52]
Hello,

I am would like report there is very weird versioning procedure, so this wasn't compatible with most packaging system eg. debian.

I would like recommend read http://semver.org/ .

Greetings,

**Comment by dequis** [comment]
These are development versions still, the releases are only done for convenience, because the first part of the git build process requires fetching the whole pidgin source from mercurial, and this can take a long time.

Prepend `0.0.0-` to the version string in your packaging scripts if this is causing problems.

**Comment by jgeboski** [comment]
I also have no intentions of doing proper versioning considering this is merely a build harness for upstream purple3.  It is easy to go off the mercurial hash as then when someone reports a bug I know exactly where to look without mapping version numbers.  This project will be dead if and when the plugin is merged into pidgin and purple3 is released.
