### ISSUE TITLE
Feature Request: Be able to add people who aren't friends

### ISSUE THREAD

**Issue by jaymzh** [jgeboski/purple-facebook#53]
There are a handful of people I speak to on messenger who I'm not facebook friends with. On FB I can see their names, but on Pidgin they come up as an FBID number... and there's no option to add them to my list, so I can't add an alias. This would be really useful.

**Comment by jgeboski** [comment]
Unfortunately, there is a lot that depends on this, namely a friend search.  It is not exactly pleasing to sniff out the identifier of someone when you want to send them a message.  The problem with Facebook is that it will not let you message anyone directly without being close to someone in the friend network.  This is mandatory for all Facebook users, and can only be made more strict via the [settings](https://www.facebook.com/settings?tab=privacy&section=messagefilter&view).

I mean, this should technically work as of now by using the raw friend identifiers, but that is by no means ideal.

**Comment by jgeboski** [comment]
I completely misread your message before my class started.  Yes, this is should be doable, I just need to reverse a method of obtaining user information based off an identifier.

**Comment by jaymzh** [comment]
Heh. Cool. I was confused by your first message, glad we're on the same page. :)

**Comment by dicecollector** [comment]
Just updating this thread with info from the duplicate thread that I created 

I discovered after recreating my Pidgin accounts and fixing Facebook (not using SMPP anymore) that if someone messages me who is not one of my friends ... it does not identify who the contact person is ... it only gives a long number ... that does not seem to be the users FB id # ... as it is several orders of magnitude higher than mine

My remedy is to goto FB and look at my current messages ... which of course does identify the sender 

Another thing I have found ... if someone who is not connected to me in any way via FB ... PM's me ... Pidgin will not even acknowledge it ... the sender receives

"Your message will go to his Other folder because you aren't connected to him on Facebook. See More"

![github fb 01](https://cloud.githubusercontent.com/assets/13302826/8802087/45f4282e-2f7c-11e5-84e1-96a0b53dd077.jpg)

**Comment by jgeboski** [comment]
This has been implemented as of [e4d77bc25235](https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/e4d77bc25235), and will appear in the next update.  It is worth noting, you will still have to initiate non-friend chats by the user identifier.  This will likely change once a friend search has been implemented.

**Comment by dicecollector** [comment]
Many thanks James ... can you tell me approximately when the next update
will occur?

Is there a way to tell if my code is out of date? ... if so ... how?

On Mon, Aug 10, 2015 at 10:41 PM, James Geboski <notifications@github.com>
wrote:

> This has been implemented as of e4d77bc25235
> <https://hg.pidgin.im/soc/2015/jgeboski/facebook/rev/e4d77bc25235>, and
> will appear in the next update. It is worth noting, you will still have to
> initiate non-friend chats by the user identifier. This will likely change
> once a friend search has been implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgeboski/purple-facebook/issues/53#issuecomment-129701313>
> .
>



-- 
<http://www.dicecollector.com/>

**Comment by jgeboski** [comment]
> Many thanks James ... can you tell me approximately when the next update will occur?

There is no time frame.  Whenever I feel like it, really.

> Is there a way to tell if my code is out of date? ... if so ... how?

Check `Help => Plugin Information`, and compare with the latest [Release](https://github.com/jgeboski/purple-facebook/releases).
